### ISSUE TITLE
You didn't install numpy.

### ISSUE THREAD

**Issue by MichaelPonGithub** [relt-1/WindowCreator#1]
I have been using this since 2020. And now when I go on to it today. And this happens. Heres the output log. Traceback (most recent call last):
  File "/lib/python3.10/_pyodide/_base.py", line 460, in eval_code
    .run(globals, locals)
  File "/lib/python3.10/_pyodide/_base.py", line 306, in run
    coroutine = eval(self.code, globals, locals)
  File "<exec>", line 5, in <module>
ModuleNotFoundError: The module 'numpy' is included in the Pyodide distribution, but it is not installed.
You can install it by calling:
  await micropip.install("numpy") in Python, or
  await pyodide.loadPackage("numpy") in JavaScript
See https://pyodide.org/en/stable/usage/loading-packages.html for more details.

/lib/python3.10/pyodide/__init__.py:74: FutureWarning: pyodide.to_js has been moved to pyodide.ffi.to_js Accessing it through the pyodide module is deprecated.
  warn(
/lib/python3.10/pyodide/__init__.py:74: FutureWarning: pyodide.create_proxy has been moved to pyodide.ffi.create_proxy Accessing it through the pyodide module is deprecated.
  warn(

**Comment by CaiozScripts** [comment]
https://replit.com/@caiozthings/WindowCreator?v=1 maybe this could help you?
